### PR TITLE
Allow usage of tap.py 3.0. Closes #20

### LINKED ISSUE #20: Bump to tappy 2.0
Once tappy 2.0 is out, bump to 2.0 so that the implicit pytest dependency is removed.

### PR DESCRIPTION
**Pull request by atodorov**

### CODE REVIEW

**Review by mblayman — CHANGES_REQUESTED** [review]
Thanks for working on this. I wasn't planning on upgrading nose-tap because nose seems to be dead/dying, but since you did the work, I'm happy to accept it.

To finish this off, could you remove the try/except imports that exist in `plugin.py` and `test_plugin.py`? They exist to protect the code from differences that exist only in Python 2, but they are no longer need. The imports themselves are still needed (e.g. `from unittest import mock`).

**Comment by atodorov** [comment]
@mblayman we still use nose/nose-tap so I am happy to do maintenance when necessary until we switch to something else.

**Review by mblayman — APPROVED** [review]
LGTM 👍

**Comment by mblayman** [comment]
I pushed up nose-tap 3.0 which includes your changes. Thanks for the contribution! https://pypi.org/project/nose-tap/3.0/

**Pull request merged**
